[27/Jun/2017 21:11:59] "GET /admin/ HTTP/1.1" 200 6934
[27/Jun/2017 21:12:04] "GET /admin/auth/user/ HTTP/1.1" 200 6887
[27/Jun/2017 21:12:04] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[27/Jun/2017 21:12:04] "GET /static/admin/img/search.svg HTTP/1.1" 304 0
[27/Jun/2017 21:12:05] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[27/Jun/2017 21:12:05] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
[27/Jun/2017 21:12:05] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
[27/Jun/2017 21:12:07] "GET /admin/ HTTP/1.1" 200 6934
Performing system checks...

System check identified no issues (0 silenced).
June 27, 2017 - 21:11:56
Django version 1.11.2, using settings 'database_project.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7f2113e4ade8>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/workspace/elections/models.py", line 32, in <module>
    admin.site.register(User)
NameError: name 'admin' is not defined
Performing system checks...

System check identified no issues (0 silenced).
June 27, 2017 - 21:15:00
Django version 1.11.2, using settings 'database_project.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[27/Jun/2017 21:15:15] "GET /admin/ HTTP/1.1" 200 7331
[27/Jun/2017 21:15:20] "GET /admin/elections/user/ HTTP/1.1" 200 4644
[27/Jun/2017 21:15:21] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[27/Jun/2017 21:15:23] "GET /admin/elections/user/lee/change/ HTTP/1.1" 200 6065
[27/Jun/2017 21:15:23] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[27/Jun/2017 21:15:23] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[27/Jun/2017 21:15:23] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[27/Jun/2017 21:15:27] "GET /admin/elections/user/ HTTP/1.1" 200 4644
[27/Jun/2017 21:15:30] "GET /admin/ HTTP/1.1" 200 7331
/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py:66: UserWarning: A {% csrf_token %} was used in a template, but the context did not provide the value.  This is usually caused by not using RequestContext.
  "A {% csrf_token %} was used in a template, but the context "
[27/Jun/2017 21:17:02] "GET /accounts/signup HTTP/1.1" 200 794
[27/Jun/2017 21:17:02] "GET /static/css/bootstrap.css HTTP/1.1" 404 1791
[27/Jun/2017 21:18:43] "GET /accounts/signup HTTP/1.1" 200 1048
[27/Jun/2017 21:18:44] "GET /static/css/bootstrap.css HTTP/1.1" 404 1791
Performing system checks...

System check identified no issues (0 silenced).
June 27, 2017 - 21:15:06
Django version 1.11.2, using settings 'database_project.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[27/Jun/2017 21:19:57] "POST /accounts/create HTTP/1.1" 302 0
[27/Jun/2017 21:19:58] "GET / HTTP/1.1" 200 1444
[27/Jun/2017 21:20:01] "GET /admin/elections/user/ HTTP/1.1" 200 4877
[27/Jun/2017 21:20:02] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[27/Jun/2017 21:20:02] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[27/Jun/2017 21:20:04] "GET /admin/elections/user/lee/change/ HTTP/1.1" 200 6065
[27/Jun/2017 21:20:04] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[27/Jun/2017 21:20:04] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[27/Jun/2017 21:20:04] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[27/Jun/2017 21:20:06] "GET /admin/elections/user/ HTTP/1.1" 200 4877
[27/Jun/2017 21:20:07] "GET /admin/elections/user/asdf/change/ HTTP/1.1" 200 6072
[27/Jun/2017 21:20:07] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[27/Jun/2017 21:20:10] "GET /admin/elections/user/ HTTP/1.1" 200 4877
[27/Jun/2017 21:20:12] "GET /admin/elections/user/John/change/ HTTP/1.1" 200 6069
[27/Jun/2017 21:20:12] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[27/Jun/2017 21:20:16] "GET /admin/elections/user/ HTTP/1.1" 200 4877
[27/Jun/2017 21:20:19] "GET /admin/ HTTP/1.1" 200 7331
[27/Jun/2017 21:20:21] "GET /admin/elections/candidate/ HTTP/1.1" 200 4673
[27/Jun/2017 21:20:22] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[27/Jun/2017 21:20:26] "GET /admin/ HTTP/1.1" 200 7331
Performing system checks...

System check identified no issues (0 silenced).
June 27, 2017 - 21:19:36
Django version 1.11.2, using settings 'database_project.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[27/Jun/2017 21:21:25] "GET /admin/ HTTP/1.1" 200 7331
[27/Jun/2017 21:21:27] "GET /admin/elections/user/ HTTP/1.1" 200 4855
[27/Jun/2017 21:21:28] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[27/Jun/2017 21:21:34] "GET /admin/elections/user/John/change/ HTTP/1.1" 200 6058
[27/Jun/2017 21:21:35] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[27/Jun/2017 21:21:40] "GET /admin/elections/user/ HTTP/1.1" 200 4855
Performing system checks...

System check identified no issues (0 silenced).
June 27, 2017 - 21:21:20
Django version 1.11.2, using settings 'database_project.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[27/Jun/2017 21:21:56] "GET /admin/elections/user/ HTTP/1.1" 200 4847
[27/Jun/2017 21:21:56] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField Poll.start_date received a naive datetime (2017-06-27 21:22:31.899182) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField Poll.end_date received a naive datetime (2017-06-27 21:22:31.899182) while time zone support is active.
  RuntimeWarning)
[27/Jun/2017 21:22:31] "GET /areas/USA/ HTTP/1.1" 200 1262
[27/Jun/2017 21:22:35] "POST /polls/1/ HTTP/1.1" 302 0
[27/Jun/2017 21:22:35] "GET /areas/USA/results HTTP/1.1" 200 870
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField Poll.start_date received a naive datetime (2017-06-27 21:25:00.470909) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField Poll.end_date received a naive datetime (2017-06-27 21:25:00.470909) while time zone support is active.
  RuntimeWarning)
[27/Jun/2017 21:25:00] "GET /areas/USA/ HTTP/1.1" 200 1262
[27/Jun/2017 21:25:06] "POST /polls/1/ HTTP/1.1" 302 0
[27/Jun/2017 21:25:06] "GET /areas/USA/results HTTP/1.1" 200 870
Performing system checks...

System check identified no issues (0 silenced).
June 27, 2017 - 21:21:53
Django version 1.11.2, using settings 'database_project.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
