Not Found: /
[16/May/2017 21:04:49] "GET / HTTP/1.1" 200 1767
Not Found: /favicon.ico
[16/May/2017 21:04:49] "GET /favicon.ico HTTP/1.1" 404 1972
Not Found: /
[16/May/2017 21:04:59] "GET / HTTP/1.1" 200 1767
Not Found: /admin
[16/May/2017 21:05:38] "GET /admin HTTP/1.1" 301 0
[16/May/2017 21:05:38] "GET /admin/ HTTP/1.1" 302 0
[16/May/2017 21:05:38] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1683
[16/May/2017 21:05:39] "GET /static/admin/css/login.css HTTP/1.1" 200 1203
[16/May/2017 21:05:39] "GET /static/admin/css/base.css HTTP/1.1" 200 15897
[16/May/2017 21:05:40] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[16/May/2017 21:05:40] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[16/May/2017 21:05:41] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
Not Found: /admin
[16/May/2017 21:07:57] "GET /admin HTTP/1.1" 301 0
[16/May/2017 21:07:58] "GET /admin/ HTTP/1.1" 302 0
[16/May/2017 21:07:58] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1683
[16/May/2017 21:07:59] "GET /static/admin/css/login.css HTTP/1.1" 200 1203
[16/May/2017 21:07:59] "GET /static/admin/css/base.css HTTP/1.1" 200 15897
[16/May/2017 21:08:00] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[16/May/2017 21:08:00] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[16/May/2017 21:08:00] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[16/May/2017 21:08:04] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[16/May/2017 21:08:05] "GET /admin/ HTTP/1.1" 200 2783
[16/May/2017 21:08:05] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 434
[16/May/2017 21:08:05] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
[16/May/2017 21:08:05] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[16/May/2017 21:08:05] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[16/May/2017 21:08:16] "GET /admin/auth/user/ HTTP/1.1" 200 6612
[16/May/2017 21:08:16] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6100
[16/May/2017 21:08:16] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[16/May/2017 21:08:16] "GET /static/admin/js/core.js HTTP/1.1" 200 8171
[16/May/2017 21:08:16] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6055
[16/May/2017 21:08:16] "GET /static/admin/js/actions.js HTTP/1.1" 200 6259
[16/May/2017 21:08:16] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7693
[16/May/2017 21:08:16] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1538
[16/May/2017 21:08:16] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 200 62474
[16/May/2017 21:08:16] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 247597
[16/May/2017 21:08:16] "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[16/May/2017 21:08:16] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[16/May/2017 21:08:17] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
[16/May/2017 21:08:17] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[16/May/2017 21:08:17] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[16/May/2017 21:08:30] "GET /admin/ HTTP/1.1" 200 2783
[16/May/2017 21:08:41] "GET /admin/auth/group/ HTTP/1.1" 200 3588
[16/May/2017 21:08:42] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
[16/May/2017 21:08:44] "GET /admin/ HTTP/1.1" 200 2783
Performing system checks...

System check identified no issues (0 silenced).
May 16, 2017 - 20:58:35
Django version 1.9, using settings 'database_project.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7f93e8a495f0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/workspace/main/models.py", line 6, in <module>
    class Post(models.Model):
  File "/home/ubuntu/workspace/main/models.py", line 11, in Post
    default=timezone.now)
NameError: name 'timezone' is not defined
Unhandled exception in thread started by <function wrapper at 0x7f8fcf4165f0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/workspace/main/models.py", line 6, in <module>
    class Post(models.Model):
  File "/home/ubuntu/workspace/main/models.py", line 11, in Post
    default=timezone.now)
NameError: name 'timezone' is not defined
